### ISSUE TITLE
Data Source Workflow Design

### ISSUE THREAD

**Issue by elatoskinas** [lightingft/appinventor-sources#10]
A conceptual design for importing data to the Data Sets should be described in the design before moving to the implementation.

The following methods should be supported:
- [x] Adding data via methods (AddEntry)
- [x] Import from Elements (#50)
- [x] Import from file (.csv) (#74)
- [x] Import from file (.json) (#92)
- [x] Import from TinyDB (#58)
- [x] Import from CloudDB (#82)
- [x] Import from online source (#57)
- [x] Real time data import (#119)
- [x] Import from List (#70)

**Comment by elatoskinas** [comment]
To be considered for later. Basic design has been done on this matter.

**Comment by elatoskinas** [comment]
CSV -> import from Chart component
Others -> Import from Data component?

Concept of Data Sink to be taken into account (Chart component can be data sink)

**Comment by elatoskinas** [comment]
Data Sink & Data Source concept should be adapted
